const tftData = {
  components: [
    { id: "bf_sword", name: "B.F.劍", icon: "https://raw.communitydragon.org/16.1/game/assets/maps/particles/tft/item_icons/standard/bf_sword.png" },
    { id: "recurve_bow", name: "反曲弓" },
    { id: "chain_vest", name: "鎖甲" },
    { id: "negatron_cloak", name: "負極斗篷" },
    { id: "giants_belt", name: "巨人腰帶" },
    { id: "needlessly_large_rod", name: "巨型魔棒" },
    { id: "tear", name: "女神之淚" },
    { id: "sparring_gloves", name: "格鬥手套" },
    { id: "frying_pan", name: "平底鍋" },
    { id: "spatula", name: "鍋鏟" }
  ],
  combined: [
    { id: "adaptive_helm", name: "適性神盔", components: ["tear", "negatron_cloak"] },
    { id: "arcanist_emblem", name: "奧術大師徽章", components: ["frying_pan", "needlessly_large_rod"] },
    { id: "archangel_s_staff", name: "大天使之杖", components: ["tear", "needlessly_large_rod"] },
    { id: "bloodthirster", name: "嗜血者", components: ["bf_sword", "negatron_cloak"] },
    { id: "blue_buff", name: "藍BUFF", components: ["tear", "tear"] },
    { id: "bramble_vest", name: "刺藤胸甲", components: ["chain_vest", "chain_vest"] },
    { id: "crownguard", name: "皇冠守衛", components: ["needlessly_large_rod", "chain_vest"] },
    { id: "deathblade", name: "死神之刃", components: ["bf_sword", "bf_sword"] },
    { id: "defender_emblem", name: "捍衛者徽章", components: ["frying_pan", "chain_vest"] },
    { id: "demacia_emblem", name: "蒂瑪西亞徽章", components: ["spatula", "chain_vest"] },
    { id: "dragon_s_claw", name: "龍之爪", components: ["negatron_cloak", "negatron_cloak"] },
    { id: "edge_of_night", name: "夜色緣界", components: ["bf_sword", "chain_vest"] },
    { id: "evenshroud", name: "均等法衣", components: ["negatron_cloak", "giants_belt"] },
    { id: "executioner_emblem", name: "征服勇士徽章", components: ["frying_pan", "sparring_gloves"] },
    { id: "freljord_emblem", name: "弗雷爾卓德徽章", components: ["spatula", "giants_belt"] },
    { id: "gargoyle_stoneplate", name: "石像鬼磐核", components: ["chain_vest", "negatron_cloak"] },
    { id: "giant_slayer", name: "巨人殺手", components: ["bf_sword", "recurve_bow"] },
    { id: "guinsoo_s_rageblade", name: "鬼索的狂暴之刃", components: ["recurve_bow", "needlessly_large_rod"] },
    { id: "hand_of_justice", name: "正義手套", components: ["sparring_gloves", "tear"] },
    { id: "hextech_gunblade", name: "海克斯科技槍刃", components: ["bf_sword", "needlessly_large_rod"] },
    { id: "infinity_edge", name: "無盡之刃", components: ["bf_sword", "sparring_gloves"] },
    { id: "invoker_emblem", name: "神諭者徽章", components: ["frying_pan", "tear"] },
    { id: "ionia_emblem", name: "愛歐尼亞徽章", components: ["spatula", "needlessly_large_rod"] },
    { id: "ionic_spark", name: "離子星火", components: ["needlessly_large_rod", "negatron_cloak"] },
    { id: "jeweled_gauntlet", name: "寶石手套", components: ["sparring_gloves", "needlessly_large_rod"] },
    { id: "juggernaut_emblem", name: "重裝戰士徽章", components: ["frying_pan", "negatron_cloak"] },
    { id: "kraken_s_fury", name: "海妖之怒", components: ["recurve_bow", "negatron_cloak"] },
    { id: "last_whisper", name: "最後耳語", components: ["recurve_bow", "sparring_gloves"] },
    { id: "morellonomicon", name: "黑魔禁書", components: ["needlessly_large_rod", "giants_belt"] },
    { id: "nashor_s_tooth", name: "納什之牙", components: ["recurve_bow", "giants_belt"] },
    { id: "noxus_emblem", name: "諾克薩斯徽章", components: ["spatula", "bf_sword"] },
    { id: "protector_s_vow", name: "保衛者之誓", components: ["chain_vest", "tear"] },
    { id: "quicksilver", name: "水銀兜帽", components: ["negatron_cloak", "sparring_gloves"] },
    { id: "quickstriker_emblem", name: "極速先鋒徽章", components: ["frying_pan", "recurve_bow"] },
    { id: "rabadon_s_deathcap", name: "死亡之帽", components: ["needlessly_large_rod", "needlessly_large_rod"] },
    { id: "red_buff", name: "紅Buff", components: ["recurve_bow", "recurve_bow"] },
    { id: "slayer_emblem", name: "殺戮者徽章", components: ["frying_pan", "bf_sword"] },
    { id: "spear_of_shojin", name: "精進之矛", components: ["bf_sword", "tear"] },
    { id: "spirit_visage", name: "振奮盔甲", components: ["tear", "giants_belt"] },
    { id: "steadfast_heart", name: "堅定之心", components: ["sparring_gloves", "chain_vest"] },
    { id: "sterak_s_gage", name: "史特拉克手套", components: ["bf_sword", "giants_belt"] },
    { id: "striker_s_flail", name: "打手連枷", components: ["giants_belt", "sparring_gloves"] },
    { id: "sunfire_cape", name: "日炎斗篷", components: ["chain_vest", "giants_belt"] },
    { id: "tactician_s_cape", name: "棋手披風", components: ["frying_pan", "spatula"] },
    { id: "tactician_s_crown", name: "棋手皇冠", components: ["spatula", "spatula"] },
    { id: "tactician_s_shield", name: "棋手之盾", components: ["frying_pan", "frying_pan"] },
    { id: "thief_s_gloves", name: "竊賊手套", components: ["sparring_gloves", "sparring_gloves"] },
    { id: "titan_s_resolve", name: "泰坦的決意", components: ["chain_vest", "recurve_bow"] },
    { id: "void_emblem", name: "虛空徽章", components: ["spatula", "recurve_bow"] },
    { id: "void_staff", name: "虛空之杖", components: ["tear", "recurve_bow"] },
    { id: "warmog_s_armor", name: "好戰者鎧甲", components: ["giants_belt", "giants_belt"] },
    { id: "yordle_emblem", name: "約德爾徽章", components: ["spatula", "negatron_cloak"] },
    { id: "zaun_emblem", name: "贊恩徽章", components: ["spatula", "sparring_gloves"] }
  ]
};

window.tftData = tftData;

