const tftData = {
  components: [
    { id: "bf_sword", name: "B.F.劍", icon: "https://raw.communitydragon.org/16.1/game/assets/maps/particles/tft/item_icons/standard/bf_sword.png" },
    { id: "recurve_bow", name: "反曲弓", icon: "https://raw.communitydragon.org/16.1/game/assets/maps/particles/tft/item_icons/standard/recurve_bow.png" },
    { id: "chain_vest", name: "鎖甲", icon: "https://raw.communitydragon.org/16.1/game/assets/maps/particles/tft/item_icons/standard/chain_vest.png" },
    { id: "negatron_cloak", name: "負極斗篷", icon: "https://raw.communitydragon.org/16.1/game/assets/maps/particles/tft/item_icons/standard/negatron_cloak.png" },
    { id: "giants_belt", name: "巨人腰帶", icon: "https://raw.communitydragon.org/16.1/game/assets/maps/particles/tft/item_icons/standard/gaints_belt.png" },
    { id: "needlessly_large_rod", name: "巨型魔棒", icon: "https://raw.communitydragon.org/16.1/game/assets/maps/particles/tft/item_icons/standard/needlessly_large_rod.png" },
    { id: "tear", name: "女神之淚", icon: "https://raw.communitydragon.org/16.1/game/assets/maps/particles/tft/item_icons/standard/tear_of_the_goddess.png" },
    { id: "sparring_gloves", name: "格鬥手套", icon: "https://raw.communitydragon.org/16.1/game/assets/maps/particles/tft/item_icons/standard/sparring_gloves.png" },
    { id: "frying_pan", name: "平底鍋", icon: "https://raw.communitydragon.org/16.1/game/assets/maps/particles/tft/item_icons/standard/frying_pan.png" },
    { id: "spatula", name: "鍋鏟", icon: "https://raw.communitydragon.org/16.1/game/assets/maps/particles/tft/item_icons/standard/spatula.png" }
  ],
  combined: [
    { id: "adaptive_helm", name: "適性神盔", components: ["tear", "negatron_cloak"], icon: "https://raw.communitydragon.org/16.1/game/assets/maps/particles/tft/item_icons/standard/adaptive_helm.png" },
    { id: "arcanist_emblem", name: "奧術大師徽章", components: ["frying_pan", "needlessly_large_rod"], icon: "https://raw.communitydragon.org/16.1/game/assets/maps/particles/tft/item_icons/traits/spatula/set16/tft16_emblem_arcanist.tft_set16.png" },
    { id: "archangel_s_staff", name: "大天使之杖", components: ["tear", "needlessly_large_rod"], icon: "https://raw.communitydragon.org/16.1/game/assets/maps/particles/tft/item_icons/standard/archangel_staff.png" },
    { id: "bloodthirster", name: "嗜血者", components: ["bf_sword", "negatron_cloak"], icon: "https://raw.communitydragon.org/16.1/game/assets/maps/particles/tft/item_icons/standard/bloodthirster.png" },
    { id: "blue_buff", name: "藍BUFF", components: ["tear", "tear"], icon: "https://raw.communitydragon.org/16.1/game/assets/maps/particles/tft/item_icons/standard/blue_buff.png" },
    { id: "bramble_vest", name: "刺藤胸甲", components: ["chain_vest", "chain_vest"], icon: "https://raw.communitydragon.org/16.1/game/assets/maps/particles/tft/item_icons/standard/bramble_vest.png" },
    { id: "crownguard", name: "皇冠守衛", components: ["needlessly_large_rod", "chain_vest"], icon: "https://raw.communitydragon.org/16.1/game/assets/maps/particles/tft/item_icons/standard/crownguard.png" },
    { id: "deathblade", name: "死神之刃", components: ["bf_sword", "bf_sword"], icon: "https://raw.communitydragon.org/16.1/game/assets/maps/particles/tft/item_icons/standard/death_blade.png" },
    { id: "defender_emblem", name: "捍衛者徽章", components: ["frying_pan", "chain_vest"], icon: "https://raw.communitydragon.org/16.1/game/assets/maps/particles/tft/item_icons/traits/spatula/set16/tft16_emblem_defender.tft_set16.png" },
    { id: "demacia_emblem", name: "蒂瑪西亞徽章", components: ["spatula", "chain_vest"], icon: "https://raw.communitydragon.org/16.1/game/assets/maps/particles/tft/item_icons/traits/spatula/set16/tft16_emblem_demacia.tft_set16.png" },
    { id: "dragon_s_claw", name: "龍之爪", components: ["negatron_cloak", "negatron_cloak"], icon: "https://raw.communitydragon.org/16.1/game/assets/maps/particles/tft/item_icons/standard/dragons_claw.png" },
    { id: "edge_of_night", name: "夜色緣界", components: ["bf_sword", "chain_vest"], icon: "https://raw.communitydragon.org/16.1/game/assets/maps/particles/tft/item_icons/standard/edge_of_night_xl.png" },
    { id: "evenshroud", name: "均等法衣", components: ["negatron_cloak", "giants_belt"], icon: "https://raw.communitydragon.org/16.1/game/assets/maps/particles/tft/item_icons/standard/support_t4_lunar.png" },
    { id: "executioner_emblem", name: "征服勇士徽章", components: ["frying_pan", "sparring_gloves"], icon: "https://raw.communitydragon.org/16.1/game/assets/maps/particles/tft/item_icons/traits/spatula/set16/tft16_emblem_vanquisher.tft_set16.png" },
    { id: "freljord_emblem", name: "弗雷爾卓德徽章", components: ["spatula", "giants_belt"], icon: "https://raw.communitydragon.org/16.1/game/assets/maps/particles/tft/item_icons/traits/spatula/set16/tft16_emblem_freljord.tft_set16.png" },
    { id: "gargoyle_stoneplate", name: "石像鬼磐核", components: ["chain_vest", "negatron_cloak"], icon: "https://raw.communitydragon.org/16.1/game/assets/maps/particles/tft/item_icons/standard/gargoyle_stoneplate.png" },
    { id: "giant_slayer", name: "巨人殺手", components: ["bf_sword", "recurve_bow"], icon: "https://raw.communitydragon.org/16.1/game/assets/maps/particles/tft/item_icons/standard/giant_slayer.png" },
    { id: "guinsoo_s_rageblade", name: "鬼索的狂暴之刃", components: ["recurve_bow", "needlessly_large_rod"], icon: "https://raw.communitydragon.org/16.1/game/assets/maps/particles/tft/item_icons/standard/guinsoos_rageblade.png" },
    { id: "hand_of_justice", name: "正義手套", components: ["sparring_gloves", "tear"], icon: "https://raw.communitydragon.org/16.1/game/assets/maps/particles/tft/item_icons/standard/hand_of_justice.png" },
    { id: "hextech_gunblade", name: "海克斯科技槍刃", components: ["bf_sword", "needlessly_large_rod"], icon: "https://raw.communitydragon.org/16.1/game/assets/maps/particles/tft/item_icons/standard/hextech_gunblade.png" },
    { id: "infinity_edge", name: "無盡之刃", components: ["bf_sword", "sparring_gloves"], icon: "https://raw.communitydragon.org/16.1/game/assets/maps/particles/tft/item_icons/standard/infinity_edge.png" },
    { id: "invoker_emblem", name: "神諭者徽章", components: ["frying_pan", "tear"], icon: "https://raw.communitydragon.org/16.1/game/assets/maps/particles/tft/item_icons/traits/spatula/set16/tft16_emblem_invoker.tft_set16.png" },
    { id: "ionia_emblem", name: "愛歐尼亞徽章", components: ["spatula", "needlessly_large_rod"], icon: "https://raw.communitydragon.org/16.1/game/assets/maps/particles/tft/item_icons/traits/spatula/set16/tft16_emblem_ionia.tft_set16.png" },
    { id: "ionic_spark", name: "離子星火", components: ["needlessly_large_rod", "negatron_cloak"], icon: "https://raw.communitydragon.org/16.1/game/assets/maps/particles/tft/item_icons/standard/ionic_spark.png" },
    { id: "jeweled_gauntlet", name: "寶石手套", components: ["sparring_gloves", "needlessly_large_rod"], icon: "https://raw.communitydragon.org/16.1/game/assets/maps/particles/tft/item_icons/standard/jeweled_guantlet.png" },
    { id: "juggernaut_emblem", name: "重裝戰士徽章", components: ["frying_pan", "negatron_cloak"], icon: "https://raw.communitydragon.org/16.1/game/assets/maps/particles/tft/item_icons/traits/spatula/set16/tft16_emblem_juggernaut.tft_set16.png" },
    { id: "kraken_s_fury", name: "海妖之怒", components: ["recurve_bow", "negatron_cloak"], icon: "https://raw.communitydragon.org/16.1/game/assets/maps/tft/icons/items/hexcore/tft_item_krakenslayerradiant.tft_tft14_5.png" },
    { id: "last_whisper", name: "最後耳語", components: ["recurve_bow", "sparring_gloves"], icon: "https://raw.communitydragon.org/16.1/game/assets/maps/particles/tft/item_icons/standard/last_whisper.png" },
    { id: "morellonomicon", name: "黑魔禁書", components: ["needlessly_large_rod", "giants_belt"], icon: "https://raw.communitydragon.org/16.1/game/assets/maps/particles/tft/item_icons/standard/morellonomicon.png" },
    { id: "nashor_s_tooth", name: "納什之牙", components: ["recurve_bow", "giants_belt"], icon: "https://raw.communitydragon.org/16.1/game/assets/maps/particles/tft/item_icons/standard/nashorstooth_xl.png" },
    { id: "noxus_emblem", name: "諾克薩斯徽章", components: ["spatula", "bf_sword"], icon: "https://raw.communitydragon.org/16.1/game/assets/maps/particles/tft/item_icons/traits/spatula/set16/tft16_emblem_noxus.tft_set16.png" },
    { id: "protector_s_vow", name: "保衛者之誓", components: ["chain_vest", "tear"], icon: "https://raw.communitydragon.org/16.1/game/assets/maps/particles/tft/item_icons/standard/winters_approach.png" },
    { id: "quicksilver", name: "水銀兜帽", components: ["negatron_cloak", "sparring_gloves"], icon: "https://raw.communitydragon.org/16.1/game/assets/maps/particles/tft/item_icons/standard/quicksilver.png" },
    { id: "quickstriker_emblem", name: "極速先鋒徽章", components: ["frying_pan", "recurve_bow"], icon: "https://raw.communitydragon.org/16.1/game/assets/maps/particles/tft/item_icons/traits/spatula/set16/tft16_emblem_quickstriker.tft_set16.png" },
    { id: "rabadon_s_deathcap", name: "死亡之帽", components: ["needlessly_large_rod", "needlessly_large_rod"], icon: "https://raw.communitydragon.org/16.1/game/assets/maps/particles/tft/item_icons/standard/rabadons_deathcap.png" },
    { id: "red_buff", name: "紅Buff", components: ["recurve_bow", "recurve_bow"], icon: "https://raw.communitydragon.org/16.1/game/assets/maps/particles/tft/item_icons/standard/redbuff.png" },
    { id: "slayer_emblem", name: "殺戮者徽章", components: ["frying_pan", "bf_sword"], icon: "https://raw.communitydragon.org/16.1/game/assets/maps/particles/tft/item_icons/traits/spatula/set16/tft16_emblem_slayer.tft_set16.png" },
    { id: "spear_of_shojin", name: "精進之矛", components: ["bf_sword", "tear"], icon: "https://raw.communitydragon.org/16.1/game/assets/maps/particles/tft/item_icons/standard/spear_of_shojin.png" },
    { id: "spirit_visage", name: "振奮盔甲", components: ["tear", "giants_belt"], icon: "https://raw.communitydragon.org/16.1/game/assets/maps/particles/tft/item_icons/standard/spiritvisage_xl.png" },
    { id: "steadfast_heart", name: "堅定之心", components: ["sparring_gloves", "chain_vest"], icon: "https://raw.communitydragon.org/16.1/game/assets/maps/particles/tft/item_icons/standard/behemoth.png" },
    { id: "sterak_s_gage", name: "史特拉克手套", components: ["bf_sword", "giants_belt"], icon: "https://raw.communitydragon.org/16.1/game/assets/maps/particles/tft/item_icons/standard/steraksgage_xl.png" },
    { id: "striker_s_flail", name: "打手連枷", components: ["giants_belt", "sparring_gloves"], icon: "https://raw.communitydragon.org/16.1/game/assets/maps/particles/tft/item_icons/standard/stridebreaker_xl.png" },
    { id: "sunfire_cape", name: "日炎斗篷", components: ["chain_vest", "giants_belt"], icon: "https://raw.communitydragon.org/16.1/game/assets/maps/particles/tft/item_icons/standard/sunfire_cape.png" },
    { id: "tactician_s_cape", name: "棋手披風", components: ["frying_pan", "spatula"], icon: "https://raw.communitydragon.org/16.1/game/assets/maps/particles/tft/item_icons/standard/tacticians_ring.png" },
    { id: "tactician_s_crown", name: "棋手皇冠", components: ["spatula", "spatula"], icon: "https://raw.communitydragon.org/16.1/game/assets/maps/particles/tft/item_icons/standard/tacticians_crown.png" },
    { id: "tactician_s_shield", name: "棋手之盾", components: ["frying_pan", "frying_pan"], icon: "https://raw.communitydragon.org/16.1/game/assets/maps/particles/tft/item_icons/standard/tacticians_scepter.png" },
    { id: "thief_s_gloves", name: "竊賊手套", components: ["sparring_gloves", "sparring_gloves"], icon: "https://raw.communitydragon.org/16.1/game/assets/maps/particles/tft/item_icons/standard/thieves_gloves.png" },
    { id: "titan_s_resolve", name: "泰坦的決意", components: ["chain_vest", "recurve_bow"], icon: "https://raw.communitydragon.org/16.1/game/assets/maps/particles/tft/item_icons/standard/titans_resolve.png" },
    { id: "void_emblem", name: "虛空徽章", components: ["spatula", "recurve_bow"], icon: "https://raw.communitydragon.org/16.1/game/assets/maps/particles/tft/item_icons/traits/spatula/set16/tft16_emblem_void.tft_set16.png" },
    { id: "void_staff", name: "虛空之杖", components: ["tear", "recurve_bow"], icon: "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/items/hexcore/tft_item_voidstaff.tft_tft14_5.png" },
    { id: "warmog_s_armor", name: "好戰者鎧甲", components: ["giants_belt", "giants_belt"], icon: "https://raw.communitydragon.org/16.1/game/assets/maps/particles/tft/item_icons/standard/warmogs_armor.png" },
    { id: "yordle_emblem", name: "約德爾徽章", components: ["spatula", "negatron_cloak"], icon: "https://raw.communitydragon.org/16.1/game/assets/maps/particles/tft/item_icons/traits/spatula/set16/tft16_emblem_yordle.tft_set16.png" },
    { id: "zaun_emblem", name: "贊恩徽章", components: ["spatula", "sparring_gloves"], icon: "https://raw.communitydragon.org/16.1/game/assets/maps/particles/tft/item_icons/traits/spatula/set16/tft16_emblem_zaun.tft_set16.png" }
  ]
};

window.tftData = tftData;
